bases:
  - ../../base
resources:
  - traefik-secret.yaml
patches:
  - traefik-ingressroute.yaml
  - traefik-persistentvolumeclaim.yaml
  - traefik-configmap.yaml
images:
- name: traefik
  newName: traefik
  newTag: 2.5.3