apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-pv-claim
  namespace: kube-system
  labels:
    app: traefik-ingress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 32Mi